"""Added backref so Roles.variables works.

Revision ID: 23dcdff2dad2
Revises: 27895d4324c8
Create Date: 2013-05-27 10:27:24.192833

"""

# revision identifiers, used by Alembic.
revision = '23dcdff2dad2'
down_revision = '27895d4324c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
