"""Variables and Roles now many-to-many.

Revision ID: 27895d4324c8
Revises: 340608d055f3
Create Date: 2013-05-27 10:21:58.547000

"""

# revision identifiers, used by Alembic.
revision = '27895d4324c8'
down_revision = '340608d055f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_variables',
    sa.Column('variable_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['variable.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.drop_column(u'variable', u'role_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'variable', sa.Column(u'role_id', sa.INTEGER(), nullable=True))
    op.drop_table('roles_variables')
    ### end Alembic commands ###
