"""Added delete cascades on Facts for Subject and Events.

Revision ID: 3048e84eead4
Revises: 36f1f1bd8a5a
Create Date: 2013-06-13 16:32:33.742472

"""

# revision identifiers, used by Alembic.
revision = '3048e84eead4'
down_revision = '36f1f1bd8a5a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
