"""Added Subject table, ExternalID table, and subject.id foreign key to Facts.

Revision ID: 33dee8e1b22c
Revises: 362ecdf08386
Create Date: 2013-06-11 10:49:27.559636

"""

# revision identifiers, used by Alembic.
revision = '33dee8e1b22c'
down_revision = '362ecdf08386'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_id')
    )
    op.create_table('externalID',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id','name', name='_subject_externalid_name_uc')
    )
    op.add_column(u'facts', sa.Column('subject_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'facts', 'subject_id')
    op.drop_table('externalID')
    op.drop_table('subject')
    ### end Alembic commands ###
