"""Added roles to variables.

Revision ID: 340608d055f3
Revises: None
Create Date: 2013-05-26 16:08:26.187043

"""

# revision identifiers, used by Alembic.
revision = '340608d055f3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('role_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variable', 'role_id')
    ### end Alembic commands ###
