"""Added Source table and many-to-many with Event and Variable.

Revision ID: 362ecdf08386
Revises: 499accc505c3
Create Date: 2013-06-07 09:28:34.281518

"""

# revision identifiers, used by Alembic.
revision = '362ecdf08386'
down_revision = '499accc505c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sources_events',
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.create_table('sources_variables',
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('variable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['variable.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.alter_column(u'variable', u'in_use',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=u'true')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'variable', u'in_use',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=u'true')
    op.drop_table('sources_variables')
    op.drop_table('sources_events')
    op.drop_table('source')
    ### end Alembic commands ###
