"""Removed not-null constraint from Event.description.

Revision ID: 36f1f1bd8a5a
Revises: 33dee8e1b22c
Create Date: 2013-06-13 10:47:23.576917

"""

# revision identifiers, used by Alembic.
revision = '36f1f1bd8a5a'
down_revision = '33dee8e1b22c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', u'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', u'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###
