"""Standardized on 'name' replacing 'unit_name' and 'display_name'

Revision ID: 3bbac6e7d8ee
Revises: 420c1fe55812
Create Date: 2013-06-06 09:40:16.556849

"""

# revision identifiers, used by Alembic.
revision = '3bbac6e7d8ee'
down_revision = '420c1fe55812'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dimension', u'unit_name', new_column_name=u'name')
    # The above replaces the next two commands.
    #op.add_column('dimension', sa.Column('name', sa.String(length=30), nullable=False))
    #op.drop_column('dimension', u'unit_name')
    op.alter_column('variable', u'display_name', new_column_name=u'name')
    #op.add_column('variable', sa.Column('name', sa.String(length=30), nullable=False))
    #op.drop_column('variable', u'display_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variable', u'name', new_column_name=u'display_name')
    #op.add_column('variable', sa.Column(u'display_name', sa.VARCHAR(length=30), nullable=False))
    #op.drop_column('variable', 'name')
    op.alter_column('dimension', u'name', new_column_name=u'unit_name')
    #op.add_column('dimension', sa.Column(u'unit_name', sa.VARCHAR(length=30), nullable=False))
    #op.drop_column('dimension', 'name')
    ### end Alembic commands ###
