"""Added is_admin to User model.

Revision ID: 403c42ff4a79
Revises: 3048e84eead4
Create Date: 2013-06-18 15:20:58.768400

"""

# revision identifiers, used by Alembic.
revision = '403c42ff4a79'
down_revision = '3048e84eead4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
