"""Added data_type ENUM to Dimension

Revision ID: 420c1fe55812
Revises: 6da215bb5f1
Create Date: 2013-05-28 15:06:53.666232

"""

# revision identifiers, used by Alembic.
revision = '420c1fe55812'
down_revision = '6da215bb5f1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    enum = postgresql.ENUM('String', 'Integer', 'Boolean', 'Float', name='dim_data_type_enum')
    enum.create(op.get_bind(), checkfirst=False)
    op.add_column('dimension', sa.Column('data_type', enum, nullable=False,
                  server_default='String'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dimension', 'data_type')
    postgresql.ENUM(name="dim_data_type_enum").drop(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###
