"""Dropped unique constraint from Variable.description.

Revision ID: 499accc505c3
Revises: 96489d0aa37
Create Date: 2013-06-06 13:18:59.903354

"""

# revision identifiers, used by Alembic.
revision = '499accc505c3'
down_revision = '96489d0aa37'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    # Drop unique constraint for Variable.description
    op.drop_constraint('variable_description_key','variable',type_='unique')
    # Drop not-null constraint for Variable.in_use
    #op.drop_constraint('2200_16528_10_not_null','variable',type_='check')


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    # Add not-null constraint for Variable.in_use
    # Name can be None due to automated naming rules.
    op.create_constraint('2200_16528_10_not_null','variable',['in_use'])
    # Add unique constraint for Variable.description
    #op.create_constraint('variable_description_key','variable',['description'])
