"""Switched User ips to String type

Revision ID: 5267f92565cb
Revises: 5abd00729c5c
Create Date: 2013-08-22 10:19:45.582257

"""

# revision identifiers, used by Alembic.
revision = '5267f92565cb'
down_revision = '5abd00729c5c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', u'last_login_ip',
               existing_type=postgresql.INET(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('user', u'current_login_ip',
               existing_type=postgresql.INET(),
               type_=sa.String(length=50),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', u'current_login_ip',
               existing_type=sa.String(length=50),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('user', u'last_login_ip',
               existing_type=sa.String(length=50),
               type_=postgresql.INET(),
               existing_nullable=True)
    ### end Alembic commands ###
