"""Added is_admin to User model.

Revision ID: 57f90b4e233f
Revises: 403c42ff4a79
Create Date: 2013-06-18 15:21:54.718853

"""

# revision identifiers, used by Alembic.
revision = '57f90b4e233f'
down_revision = '403c42ff4a79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
