"""empty message

Revision ID: 5abd00729c5c
Revises: 57f90b4e233f
Create Date: 2013-06-18 15:28:01.081139

"""

# revision identifiers, used by Alembic.
revision = '5abd00729c5c'
down_revision = '57f90b4e233f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(),
                 server_default='0'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'is_admin')
    ### end Alembic commands ###
