"""Added Event table with foreign key in Facts.

Revision ID: 96489d0aa37
Revises: 3bbac6e7d8ee
Create Date: 2013-06-06 11:36:35.557406

"""

# revision identifiers, used by Alembic.
revision = '96489d0aa37'
down_revision = '3bbac6e7d8ee'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    Event = sa.sql.table('event',
                  sa.sql.column('name', sa.String(80)),
                  sa.sql.column('description', sa.String(255))
                 )
    op.bulk_insert(Event,
    [
        {'id':'1', 'name':'First Event',
         'description':'The first event.'},
    ])

    op.add_column(u'facts', sa.Column('event_id', sa.Integer(), nullable=False,
                                     server_default='1'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'facts', 'event_id')
    op.drop_table('event')
    ### end Alembic commands ###
