"""Drop 'reviewed' from Facts table.

Revision ID: efda3e6ba54
Revises: 5267f92565cb
Create Date: 2013-08-29 17:47:37.845978

"""

# revision identifiers, used by Alembic.
revision = 'efda3e6ba54'
down_revision = '5267f92565cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facts', u'reviewed')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facts', sa.Column(u'reviewed', sa.BOOLEAN(), nullable=False))
    ### end Alembic commands ###
